spring:
  application:
    name: sample-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka/

server:
  port: 8888

management:
  port: 9000
  address: 127.0.0.1