spring:
  application:
    name: sample-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/,http://localhost:10011/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10

server:
  port: 8888

management:
  port: 9000
  address: 127.0.0.1