spring:
  application:
    name: eureka-server

server:
  port: 100010

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
