server:
  port: 10000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
