spring:
  application:
    name: eureka-server

server:
  port: 10011

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/
    register-with-eureka: true
    fetch-registry: true